server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calyee_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1qiulihang
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  #Redis相关配置
  redis:
    host: localhost
    port: 6379
    #password:123456
    database: 0 #0是0号数据库，redis默认开启的16个数据库
    jedis:
      #Redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中最大空闲连接
        min-idle: 0 #连接池中最小空闲连接
  cache:
    redis:
      time-to-live: 1800000 #设置缓存有效期1800秒 1800 000毫秒
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# 七牛云 (已废弃)
oss:
  accessKey: cuwMLlcQi3v83Q9WmNeqn2FSq2TCvE8C5ok7McfH
  secretKey: V-LBcGJAuptis_hXNsWLuuJg-wioAEBsN9zFiMKT
  bucket: calyee-blog
# 上传到 linux 服务器
file:
  localUrl: E:/Ai/images/
  linuxUrl: /usr/local/blog-images/